name: c
on: push
jobs:
  project:
    runs-on: ubuntu-24.04
    steps:
      - name: Build
        run: echo "Building"
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: echo "Deploying
