name: Greeting Workflow
on: push
jobs:
  akshatgreet:
      runs-on: ubuntu-latest
      steps:
        - name: greet user
          run: echssssssso "hello world"
  secondjob:
       needs: akshatgreet
       runs-on:  ubuntu-24.04
       steps:
           - name: second job
             run: echo "this is the second job"
  
