name: Greeting Workflow
on: push
jobs:
  akshatgreet:
      runs-on: ubuntu-latest
      steps:
        - name: greet user
          run: echo "hello world"
  secondjob:
       runs-on:  
       steps:
           - name: second job
             run: echo "this is the second job"
  
